--- 
name: "Teamserver/Client Bug Report"
title: "[Teamserver-Client--Bug]: "
labels: ["clientside/teamserver"]

assignees: 
  - C5pider
body: 
  - 
    attributes: 
      value: "Thanks for taking the time to fill out this bug report!\n"
    type: markdown
  - 
    attributes: 
      description: "How can we get in touch with you if we need more info?"
      label: "Contact Details"
      placeholder: "ex. email@example.com"
    id: contact
    type: input
    validations: 
      required: false
  - 
    attributes: 
      description: "Also tell us, what did you expect to happen?"
      label: "What happened?"
      placeholder: "Tell me about the numbers Mason!"
      value: "A bug happened!"
    id: what-happened
    type: textarea
    validations: 
      required: true
  - 
    attributes: 
      description: "What version of our software are you running?"
      label: Did_You_Do_a_Pull_First?
      options: 
        - "Latest (You performed a pull first)"
        - "Anything else (You didn't pull...)"
    id: version
    type: dropdown
    validations: 
      required: true
  - 
    attributes: 
      description: "Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks."
      label: "Relevant log output"
      render: shell
    id: logs
    type: textarea
  - 
    attributes: 
      description: "By submitting this issue, you declare you posted replication steps and information about the issue, so that it may be fully understood ."
      label: Did-You-Read-Over-Your-Issue-First?
      options: 
        - 
          label: "I declare I made an effort and provided the necessary information for replication of the issue."
          required: true
